name: dirac-env  
channels:
  - defaults
dependencies:
  - python=3.9
  - r-base=4.3.1
  - rpy2
  - r-mclust
  - r-yarrr
  - pip:
      - torch==2.1.0 --index-url https://download.pytorch.org/whl/cu118
      - torchvision==0.16.0 --index-url https://download.pytorch.org/whl/cu118
      - torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu118
      - pyg_lib==0.3.1+pt21cu118 --index-url https://data.pyg.org/whl/torch-2.1.0+cu118.html
      - torch_scatter --index-url https://data.pyg.org/whl/torch-2.1.0+cu118.html
      - torch_sparse --index-url https://data.pyg.org/whl/torch-2.1.0+cu118.html
      - torch_cluster --index-url https://data.pyg.org/whl/torch-2.1.0+cu118.html
      - torch_spline_conv --index-url https://data.pyg.org/whl/torch-2.1.0+cu118.html
      - torch_geometric==2.3.1
